import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    clients: 'Clients',
    fournisseurs: 'Fournisseurs',
    produits: 'Produits',
    commandes: 'Commandes',
    devis: 'Devis',
    achats: 'Achats',
    stock: 'Stock',
    finance: 'Finance',
    utilisateurs: 'Utilisateurs',
    documents: 'Documents',
    archives: 'Archives',
    notifications: 'Notifications',
    parametres: 'Paramètres',
    deconnexion: 'Déconnexion',

    // Sections
    navigation: 'Navigation',
    ventes: 'Ventes',
    administration: 'Administration',

    // Actions génériques
    creer: 'Créer',
    modifier: 'Modifier',
    supprimer: 'Supprimer',
    valider: 'Valider',
    annuler: 'Annuler',
    enregistrer: 'Enregistrer',
    rechercher: 'Rechercher',
    exporter: 'Exporter',
    imprimer: 'Imprimer',
    telecharger: 'Télécharger',
    retour: 'Retour',
    actions: 'Actions',
    ajouter: 'Ajouter',
    fermer: 'Fermer',
    ouvrir: 'Ouvrir',
    appliquer: 'Appliquer',
    reinitialiser: 'Réinitialiser',
    aucun: 'Aucun',
    non_specifie: 'Non spécifié',

    // États
    en_attente: 'En attente',
    confirmee: 'Confirmée',
    livree: 'Livrée',
    annulee: 'Annulée',
    annule: 'Annulé',
    actif: 'Actif',
    inactif: 'Inactif',
    brouillon: 'Brouillon',
    envoye: 'Envoyé',
    accepte: 'Accepté',
    refuse: 'Refusé',
    expire: 'Expiré',
    tous: 'Tous',
    valide: 'Validé',
    echoue: 'Échoué',
    rembourse: 'Remboursé',
    en_cours: 'En cours',
    termine: 'Terminé',
    a_faire: 'À faire',
    bloque: 'Bloqué',

    // Général
    total: 'Total',
    montant: 'Montant',
    date: 'Date',
    statut: 'Statut',
    nom: 'Nom',
    prenom: 'Prénom',
    email: 'Email',
    telephone: 'Téléphone',
    adresse: 'Adresse',
    description: 'Description',
    prix: 'Prix',
    quantite: 'Quantité',
    notes: 'Notes',
    categorie: 'Catégorie',
    mode_paiement: 'Mode de paiement',
    source: 'Source',
    type: 'Type',

    // Messages
    chargement: 'Chargement...',
    aucune_donnee: 'Aucune donnée',
    erreur_serveur: 'Erreur serveur',
    succes: 'Succès',
    confirmation_suppression: 'Confirmer la suppression ?',
    page: 'Page',
    filtrer_par: 'Filtrer par',

    // ===== Module Fournisseurs =====
    gestion_fournisseurs: 'Gestion des Fournisseurs',
    gerer_fournisseurs: 'Gérez tous vos fournisseurs',
    nouveau_fournisseur: 'Nouveau fournisseur',
    modifier_fournisseur: 'Modifier le fournisseur',
    fournisseur_cree: 'Fournisseur créé avec succès',
    fournisseur_modifie: 'Fournisseur mis à jour avec succès',
    fournisseur_supprime: 'Fournisseur supprimé',
    liste_fournisseurs: 'Liste des fournisseurs',

    // ===== Module Clients =====
    gestion_clients: 'Gestion des clients',
    gerer_clients: 'Gérez tous vos clients',
    nouveau_client: 'Nouveau client',
    modifier_client: 'Modifier le client',
    client_cree: 'Client créé avec succès',
    client_modifie: 'Client modifié avec succès',
    client_supprime: 'Client supprimé',
    choisir_client: 'Choisir un client',

    // ===== Module Commandes =====
    gestion_commandes: 'Gestion des commandes',
    gerer_commandes: 'Gérez toutes les commandes de votre entreprise',
    nouvelle_commande: 'Nouvelle commande',
    commande_cree: 'Commande créée avec succès',
    commande_supprimee: 'Commande supprimée',
    liste_commandes: 'Liste des commandes',
    changer_statut: 'Changer statut',
    payer: 'Payer',
    ajouter_produit: 'Ajouter un produit',

    // ===== Module Devis =====
    gestion_devis: 'Gestion des Devis',
    gerer_devis: 'Gérez tous vos devis',
    nouveau_devis: 'Nouveau devis',
    devis_cree: 'Devis créé avec succès',
    devis_supprime: 'Devis supprimé',
    devis_converti: 'Devis converti en commande',
    liste_devis: 'Liste des devis',
    date_validite: 'Date de validité',
    convertir_commande: 'Convertir en commande',
    remise: 'Remise (%)',
    notes_supplementaires: 'Notes supplémentaires',

    // ===== Module Entrepôts / Stock =====
    gestion_entrepots: 'Gestion des Entrepôts',
    gerer_entrepots: 'Gérez vos entrepôts et leur stock',
    nouvel_entrepot: 'Nouvel entrepôt',
    modifier_entrepot: "Modifier l'entrepôt",
    entrepot_cree: 'Entrepôt créé avec succès',
    entrepot_modifie: 'Entrepôt mis à jour avec succès',
    entrepot_supprime: 'Entrepôt supprimé',
    liste_entrepots: 'Liste des entrepôts',
    gestion_stock: 'Gestion du stock',
    choisir_produit: 'Choisir un produit',
    stock_actuel: 'Stock actuel',
    stock_vide: 'Cet entrepôt est vide.',
    gestion_produits: 'Gestion des Produits',
    gerer_produits: 'Gérez votre catalogue produits',
    nouveau_produit: 'Nouveau produit',
    modifier_produit: 'Modifier le produit',
    produit_cree: 'Produit créé avec succès',
    produit_modifie: 'Produit mis à jour avec succès',
    produit_supprime: 'Produit supprimé',
    catalogue_produits: 'Catalogue des produits',
    quantite_stock: 'Quantité en stock',
    rupture: 'rupture',
    critique: 'Critique',
    bas: 'Bas',
    normal: 'Normal',
    gestion_inventaires: 'Gestion des inventaires',
    historique_stock: 'Historique des stocks',
    alerte_rupture: 'Alerte de rupture',
    transfert_stock: 'Transfert de stock',
    entrepots_label: 'Entrepôts',
    moteur_calcul: 'Moteur de calcul',
    mouvements_stock: 'Mouvements de stock',
    inventaire: 'Inventaire',
    calculateur: 'Calculateur',

    // ===== Dashboard =====
    bonjour: 'Bonjour',
    enregistres: 'enregistrés',
    references: 'références',
    aucune_alerte: 'Aucune alerte',
    produits_critiques: 'produit(s) critique(s)',
    acces_rapide: 'Accès rapide',
    actualiser: 'Actualiser',
    exporter_donnees: 'Exporter mes données',
    erreur_export: "Erreur lors de l'export",
    export_succes: 'Données exportées avec succès',
    promotions: 'Promotions',
    promotions_actives: 'Promotions actives',
    actives: 'actives',
    alertes_stock: 'Alertes stock',
    achats_en_cours: 'Achats en cours',
    gestion_documentaire: 'Gestion documentaire',
    archivage_numerique: 'Archivage numérique',
    gestion_acces: "Gestion des accès",
    alertes: 'Alertes',

    // ===== Essai expiré =====
    essai_expire_titre: "Votre période d'essai gratuite est terminée",
    essai_expire_message: 'Vous avez utilisé vos 30 connexions gratuites',
    pour: 'pour',
    essai_expire_donnees: "Aucune donnée n'a été perdue",
    essai_expire_conserve: 'tout ce que vous avez ajouté reste enregistré.',
    exporter_mes_donnees: 'Exporter mes données',
    souscrire_abonnement: 'Souscrire à un abonnement',
    erreur_export_donnees: "Impossible d'exporter vos données pour le moment.",

    // ===== Module Finance =====
    gestion_finance: 'Gestion financière',
    gerer_finance: 'Comptabilité, paiements, dépenses et recettes',
    rapport: 'Rapport',
    depenses: 'Dépenses',
    recettes: 'Recettes',
    paiements: 'Paiements',
    filtrer_periode: 'Filtrer par période',
    date_debut: 'Date début',
    date_fin: 'Date fin',
    total_recettes: 'Total recettes',
    total_depenses: 'Total dépenses',
    resultat_net: 'Résultat net',
    detail_recettes: 'Détail des recettes',
    commandes_livrees: 'Commandes livrées',
    recettes_manuelles: 'Recettes manuelles',
    depenses_par_categorie: 'Dépenses par catégorie',
    aucune_depense: 'Aucune dépense enregistrée sur cette période.',
    nouvelle_depense: 'Nouvelle dépense',
    liste_depenses: 'Liste des dépenses',
    modifier_depense: 'Modifier la dépense',
    depense_cree: 'Dépense enregistrée avec succès',
    depense_modifiee: 'Dépense mise à jour avec succès',
    depense_supprimee: 'Dépense supprimée',
    nouvelle_recette: 'Nouvelle recette',
    liste_recettes: 'Liste des recettes',
    recette_cree: 'Recette enregistrée avec succès',
    recette_supprimee: 'Recette supprimée',
    exemple_source: 'Ex: Subvention, Remboursement...',
    enregistrer_paiement: 'Enregistrer un paiement',
    liste_paiements: 'Liste des paiements',
    numero_transaction: 'N° Transaction',
    commande: 'Commande',
    achat: 'Achat',
    nouveau_paiement: 'Nouveau paiement',
    type_reference: 'Type de référence',
    commande_client: 'Commande client',
    achat_fournisseur: 'Achat fournisseur',
    id_reference: 'ID de référence',
    paiement_attention: 'Les modes Stripe, PayPal, Flouci et Konnect créent un paiement "en attente" jusqu\'à confirmation du fournisseur de paiement.',
    paiement_cree: 'Paiement enregistré',
    statut_paiement_modifie: 'Statut du paiement mis à jour',

    // ===== Auth =====
    login: 'Se connecter',
    register: "S'inscrire",
    password: 'Mot de passe',
    forgot_password: 'Mot de passe oublié ?',
    create_account: 'Créer un compte entreprise',
    or: 'ou',
    all_rights_reserved: 'Tous droits réservés',
    erreur_connexion: 'Erreur de connexion',
    email_ou_password_incorrect: 'Email ou mot de passe incorrect',

    // ===== Pages diverses =====
    bienvenue: 'Bienvenue',
    espace_client: 'Espace client',
    profil: 'Profil',
    factures: 'Factures',
    securite_mfa: 'Sécurité MFA',
    


    login_titre: 'Plateforme de gestion d\'entreprise',
    email_professionnel: 'Email professionnel',
    mot_de_passe: 'Mot de passe',
    connexion_en_cours: 'Connexion en cours...',
    se_connecter: 'Se connecter',
    mot_de_passe_oublie: 'Mot de passe oublié ?',
    creer_compte_entreprise: 'Créer un compte entreprise',
    deja_compte: 'Déjà un compte ? Se connecter',
    tous_droits_reserves: 'Tous droits réservés',

    // Register
    creer_mon_compte: 'Créer mon compte',
    inscrire_entreprise: 'Inscrivez votre entreprise en quelques minutes',
    infos_entreprise: 'Informations de l\'entreprise',
    nom_entreprise: 'Nom de l\'entreprise',
    compte_administrateur: 'Compte administrateur',
    choisir_formule: 'Choisissez votre formule',
    essai_gratuit: 'Essai gratuit',
    connexions_gratuites: '30 connexions gratuites',
    sans_engagement: 'Sans engagement',
    abonnement: 'Abonnement',
    acces_illimite: 'Accès illimité',
    inscription_en_cours: 'Inscription en cours...',
    sinscrire: 'S\'inscrire',

    alertes_rupture_stock: 'Alertes de rupture de stock',
    surveillez_produits_risque: 'Surveillez les produits à risque',
    rafraichir: 'Rafraîchir',
    produits_en_alerte: 'Produits en alerte',
    en_rupture_totale: 'En rupture totale',
    pas_alerte_rupture: 'Pas d\'alerte de rupture',
    tous_produits_stock_suffisant: 'Tous vos produits ont un stock suffisant.',
    commander: 'Commander',
    stock_actuel_label: 'Stock actuel',
    niveau: 'Niveau',
    rupture_totale: 'Rupture',
    tres_critique: 'Très critique',
    critique_niveau: 'Critique',
    bas_niveau: 'Bas',

    historique_mouvements: 'Historique des mouvements par produit',
    ajuster_stock: 'Ajuster le stock',
    selectionner_produit_titre: 'Sélectionner un produit',
    choisir_produit_placeholder: '-- Sélectionner un produit --',
    quantite_entree_sortie: 'Quantité (+ entrée, - sortie) *',
    motif_ajustement: 'Motif *',
    raison_ajustement: 'Raison de l\'ajustement',
    appliquer_ajustement: 'Appliquer l\'ajustement',
    historique_mouvements_produit: 'Historique des mouvements',
    type: 'Type',
    ancien_stock: 'Ancien stock',
    nouveau_stock: 'Nouveau stock',
    par: 'Par',
    entree: 'Entrée',
    sortie: 'Sortie',
    ajustement: 'Ajustement',
    commande_client_type: 'Commande client',
    achat_fournisseur_type: 'Achat fournisseur',
    stock_ajuste_succes: 'Stock ajusté avec succès',

    transfert_stock_titre: 'Transfert de stock',
    transferer_stock_desc: 'Transférez du stock d\'un entrepôt à un autre',
    acces_refuse_titre: 'Accès refusé',
    pas_permission_transfert: 'Vous n\'avez pas la permission de transférer du stock.',
    nouveau_transfert: 'Nouveau transfert',
    entrepot_source: 'Entrepôt source *',
    entrepot_destination: 'Entrepôt destination *',
    source_placeholder: '-- Source --',
    destination_placeholder: '-- Destination --',
    stock_disponible: 'Stock disponible',
    aucun_stock: 'Aucun stock',
    ajoutez_stock_source: 'Ajoutez du stock dans l\'entrepôt source d\'abord',
    effectuer_transfert: 'Effectuer le transfert',
    transfert_en_cours: 'Transfert en cours...',
    transfert_effectue: 'Transfert effectué avec succès',
    stock_insuffisant: 'Stock insuffisant',
    quantite_superieure_zero: 'La quantité doit être supérieure à 0',
    produit_sans_stock_source: 'Ce produit n\'a pas de stock dans l\'entrepôt source sélectionné.',
  },

  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    fournisseurs: 'Suppliers',
    produits: 'Products',
    commandes: 'Orders',
    devis: 'Quotes',
    achats: 'Purchases',
    stock: 'Stock',
    finance: 'Finance',
    utilisateurs: 'Users',
    documents: 'Documents',
    archives: 'Archives',
    notifications: 'Notifications',
    parametres: 'Settings',
    deconnexion: 'Logout',

    navigation: 'Navigation',
    ventes: 'Sales',
    administration: 'Administration',

    creer: 'Create',
    modifier: 'Edit',
    supprimer: 'Delete',
    valider: 'Validate',
    annuler: 'Cancel',
    enregistrer: 'Save',
    rechercher: 'Search',
    exporter: 'Export',
    imprimer: 'Print',
    telecharger: 'Download',
    retour: 'Back',
    actions: 'Actions',
    ajouter: 'Add',
    fermer: 'Close',
    ouvrir: 'Open',
    appliquer: 'Apply',
    reinitialiser: 'Reset',
    aucun: 'None',
    non_specifie: 'Not specified',

    en_attente: 'Pending',
    confirmee: 'Confirmed',
    livree: 'Delivered',
    annulee: 'Cancelled',
    annule: 'Cancelled',
    actif: 'Active',
    inactif: 'Inactive',
    brouillon: 'Draft',
    envoye: 'Sent',
    accepte: 'Accepted',
    refuse: 'Refused',
    expire: 'Expired',
    tous: 'All',
    valide: 'Validated',
    echoue: 'Failed',
    rembourse: 'Refunded',
    en_cours: 'In progress',
    termine: 'Finished',
    a_faire: 'To do',
    bloque: 'Blocked',

    total: 'Total',
    montant: 'Amount',
    date: 'Date',
    statut: 'Status',
    nom: 'Name',
    prenom: 'First name',
    email: 'Email',
    telephone: 'Phone',
    adresse: 'Address',
    description: 'Description',
    prix: 'Price',
    quantite: 'Quantity',
    notes: 'Notes',
    categorie: 'Category',
    mode_paiement: 'Payment method',
    source: 'Source',
    type: 'Type',

    chargement: 'Loading...',
    aucune_donnee: 'No data',
    erreur_serveur: 'Server error',
    succes: 'Success',
    confirmation_suppression: 'Confirm deletion?',
    page: 'Page',
    filtrer_par: 'Filter by',

    // Suppliers
    gestion_fournisseurs: 'Supplier Management',
    gerer_fournisseurs: 'Manage all your suppliers',
    nouveau_fournisseur: 'New supplier',
    modifier_fournisseur: 'Edit supplier',
    fournisseur_cree: 'Supplier created successfully',
    fournisseur_modifie: 'Supplier updated successfully',
    fournisseur_supprime: 'Supplier deleted',
    liste_fournisseurs: 'Supplier list',

    // Clients
    gestion_clients: 'Client management',
    gerer_clients: 'Manage all your clients',
    nouveau_client: 'New client',
    modifier_client: 'Edit client',
    client_cree: 'Client created successfully',
    client_modifie: 'Client updated successfully',
    client_supprime: 'Client deleted',
    choisir_client: 'Choose a client',

    // Orders
    gestion_commandes: 'Order management',
    gerer_commandes: 'Manage all your company orders',
    nouvelle_commande: 'New order',
    commande_cree: 'Order created successfully',
    commande_supprimee: 'Order deleted',
    liste_commandes: 'Order list',
    changer_statut: 'Change status',
    payer: 'Pay',
    ajouter_produit: 'Add a product',

    // Quotes
    gestion_devis: 'Quote Management',
    gerer_devis: 'Manage all your quotes',
    nouveau_devis: 'New quote',
    devis_cree: 'Quote created successfully',
    devis_supprime: 'Quote deleted',
    devis_converti: 'Quote converted to order',
    liste_devis: 'Quote list',
    date_validite: 'Validity date',
    convertir_commande: 'Convert to order',
    remise: 'Discount (%)',
    notes_supplementaires: 'Additional notes',

    // Warehouses / Stock
    gestion_entrepots: 'Warehouse Management',
    gerer_entrepots: 'Manage your warehouses and their stock',
    nouvel_entrepot: 'New warehouse',
    modifier_entrepot: 'Edit warehouse',
    entrepot_cree: 'Warehouse created successfully',
    entrepot_modifie: 'Warehouse updated successfully',
    entrepot_supprime: 'Warehouse deleted',
    liste_entrepots: 'Warehouse list',
    gestion_stock: 'Stock management',
    choisir_produit: 'Choose a product',
    stock_actuel: 'Current stock',
    stock_vide: 'This warehouse is empty.',
    gestion_produits: 'Product Management',
    gerer_produits: 'Manage your product catalog',
    nouveau_produit: 'New product',
    modifier_produit: 'Edit product',
    produit_cree: 'Product created successfully',
    produit_modifie: 'Product updated successfully',
    produit_supprime: 'Product deleted',
    catalogue_produits: 'Product catalog',
    quantite_stock: 'Stock quantity',
    rupture: 'out of stock',
    critique: 'Critical',
    bas: 'Low',
    normal: 'Normal',
    gestion_inventaires: 'Inventory management',
    historique_stock: 'Stock history',
    alerte_rupture: 'Stock alert',
    transfert_stock: 'Stock transfer',
    entrepots_label: 'Warehouses',
    moteur_calcul: 'Calculation engine',
    mouvements_stock: 'Stock movements',
    inventaire: 'Inventory',
    calculateur: 'Calculator',

    // Dashboard
    bonjour: 'Hello',
    enregistres: 'recorded',
    references: 'references',
    aucune_alerte: 'No alerts',
    produits_critiques: 'critical product(s)',
    acces_rapide: 'Quick access',
    actualiser: 'Refresh',
    exporter_donnees: 'Export my data',
    erreur_export: 'Export error',
    export_succes: 'Data exported successfully',
    promotions: 'Promotions',
    promotions_actives: 'Active promotions',
    actives: 'active',
    alertes_stock: 'Stock alerts',
    achats_en_cours: 'Purchases in progress',
    gestion_documentaire: 'Document management',
    archivage_numerique: 'Digital archiving',
    gestion_acces: 'Access management',
    alertes: 'Alerts',

    // Trial expired
    essai_expire_titre: 'Your free trial period has ended',
    essai_expire_message: 'You have used your 30 free connections',
    pour: 'for',
    essai_expire_donnees: 'No data has been lost',
    essai_expire_conserve: 'everything you added remains saved.',
    exporter_mes_donnees: 'Export my data',
    souscrire_abonnement: 'Subscribe to a plan',
    erreur_export_donnees: 'Unable to export your data at this time.',

    // Finance
    gestion_finance: 'Financial management',
    gerer_finance: 'Accounting, payments, expenses and revenue',
    rapport: 'Report',
    depenses: 'Expenses',
    recettes: 'Revenue',
    paiements: 'Payments',
    filtrer_periode: 'Filter by period',
    date_debut: 'Start date',
    date_fin: 'End date',
    total_recettes: 'Total revenue',
    total_depenses: 'Total expenses',
    resultat_net: 'Net result',
    detail_recettes: 'Revenue details',
    commandes_livrees: 'Delivered orders',
    recettes_manuelles: 'Manual revenue',
    depenses_par_categorie: 'Expenses by category',
    aucune_depense: 'No expenses recorded for this period.',
    nouvelle_depense: 'New expense',
    liste_depenses: 'Expense list',
    modifier_depense: 'Edit expense',
    depense_cree: 'Expense recorded successfully',
    depense_modifiee: 'Expense updated successfully',
    depense_supprimee: 'Expense deleted',
    nouvelle_recette: 'New revenue',
    liste_recettes: 'Revenue list',
    recette_cree: 'Revenue recorded successfully',
    recette_supprimee: 'Revenue deleted',
    exemple_source: 'E.g.: Grant, Refund...',
    enregistrer_paiement: 'Record a payment',
    liste_paiements: 'Payment list',
    numero_transaction: 'Transaction #',
    commande: 'Order',
    achat: 'Purchase',
    nouveau_paiement: 'New payment',
    type_reference: 'Reference type',
    commande_client: 'Client order',
    achat_fournisseur: 'Supplier purchase',
    id_reference: 'Reference ID',
    paiement_attention: 'Stripe, PayPal, Flouci and Konnect payment methods create a "pending" payment until confirmed by the payment provider.',
    paiement_cree: 'Payment recorded',
    statut_paiement_modifie: 'Payment status updated',

    // Auth
    login: 'Login',
    register: 'Register',
    password: 'Password',
    forgot_password: 'Forgot password?',
    create_account: 'Create company account',
    or: 'or',
    all_rights_reserved: 'All rights reserved',
    erreur_connexion: 'Connection error',
    email_ou_password_incorrect: 'Invalid email or password',

    bienvenue: 'Welcome',
    espace_client: 'Client space',
    profil: 'Profile',
    factures: 'Invoices',
    securite_mfa: 'MFA Security',

  // en (mêmes clés, valeurs anglaises)
    login_titre: 'Business management platform',
    email_professionnel: 'Professional email',
    mot_de_passe: 'Password',
    connexion_en_cours: 'Signing in...',
    se_connecter: 'Sign in',
    mot_de_passe_oublie: 'Forgot password?',
    creer_compte_entreprise: 'Create a company account',
    deja_compte: 'Already have an account? Sign in',
    tous_droits_reserves: 'All rights reserved',
    creer_mon_compte: 'Create my account',
    inscrire_entreprise: 'Register your company in a few minutes',
    infos_entreprise: 'Company information',
    nom_entreprise: 'Company name',
    compte_administrateur: 'Administrator account',
    choisir_formule: 'Choose your plan',
    essai_gratuit: 'Free trial',
    connexions_gratuites: '30 free logins',
    sans_engagement: 'No commitment',
    abonnement: 'Subscription',
    acces_illimite: 'Unlimited access',
    inscription_en_cours: 'Registering...',
    sinscrire: 'Sign up',

    alertes_rupture_stock: 'Stock shortage alerts',
    surveillez_produits_risque: 'Monitor at-risk products',
    rafraichir: 'Refresh',
    produits_en_alerte: 'Products on alert',
    en_rupture_totale: 'Completely out of stock',
    pas_alerte_rupture: 'No shortage alerts',
    tous_produits_stock_suffisant: 'All your products have sufficient stock.',
    commander: 'Order',
    stock_actuel_label: 'Current stock',
    niveau: 'Level',
    rupture_totale: 'Out of stock',
    tres_critique: 'Very critical',
    critique_niveau: 'Critical',
    bas_niveau: 'Low',

    historique_mouvements: 'View movement history per product',
    ajuster_stock: 'Adjust stock',
    selectionner_produit_titre: 'Select a product',
    choisir_produit_placeholder: '-- Select a product --',
    quantite_entree_sortie: 'Quantity (+ in, - out) *',
    motif_ajustement: 'Reason *',
    raison_ajustement: 'Reason for the adjustment',
    appliquer_ajustement: 'Apply adjustment',
    historique_mouvements_produit: 'Movement history',
    type: 'Type',
    ancien_stock: 'Previous stock',
    nouveau_stock: 'New stock',
    par: 'By',
    entree: 'In',
    sortie: 'Out',
    ajustement: 'Adjustment',
    commande_client_type: 'Customer order',
    achat_fournisseur_type: 'Supplier purchase',
    stock_ajuste_succes: 'Stock adjusted successfully',

    transfert_stock_titre: 'Stock transfer',
    transferer_stock_desc: 'Transfer stock from one warehouse to another',
    acces_refuse_titre: 'Access denied',
    pas_permission_transfert: 'You do not have permission to transfer stock.',
    nouveau_transfert: 'New transfer',
    entrepot_source: 'Source warehouse *',
    entrepot_destination: 'Destination warehouse *',
    source_placeholder: '-- Source --',
    destination_placeholder: '-- Destination --',
    stock_disponible: 'Available stock',
    aucun_stock: 'No stock',
    ajoutez_stock_source: 'Add stock to the source warehouse first',
    effectuer_transfert: 'Perform transfer',
    transfert_en_cours: 'Transfer in progress...',
    transfert_effectue: 'Transfer completed successfully',
    stock_insuffisant: 'Insufficient stock',
    quantite_superieure_zero: 'Quantity must be greater than 0',
    produit_sans_stock_source: 'This product has no stock in the selected source warehouse.',
  },

  ar: {
    dashboard: 'لوحة القيادة',
    clients: 'العملاء',
    fournisseurs: 'الموردون',
    produits: 'المنتجات',
    commandes: 'الطلبات',
    devis: 'عروض الأسعار',
    achats: 'المشتريات',
    stock: 'المخزون',
    finance: 'المالية',
    utilisateurs: 'المستخدمون',
    documents: 'المستندات',
    archives: 'الأرشيف',
    notifications: 'الإشعارات',
    parametres: 'الإعدادات',
    deconnexion: 'تسجيل الخروج',

    navigation: 'التنقل',
    ventes: 'المبيعات',
    administration: 'الإدارة',

    creer: 'إنشاء',
    modifier: 'تعديل',
    supprimer: 'حذف',
    valider: 'تأكيد',
    annuler: 'إلغاء',
    enregistrer: 'حفظ',
    rechercher: 'بحث',
    exporter: 'تصدير',
    imprimer: 'طباعة',
    telecharger: 'تحميل',
    retour: 'رجوع',
    actions: 'إجراءات',
    ajouter: 'إضافة',
    fermer: 'إغلاق',
    ouvrir: 'فتح',
    appliquer: 'تطبيق',
    reinitialiser: 'إعادة تعيين',
    aucun: 'لا شيء',
    non_specifie: 'غير محدد',

    en_attente: 'قيد الانتظار',
    confirmee: 'مؤكد',
    livree: 'تم التسليم',
    annulee: 'ملغى',
    annule: 'ملغى',
    actif: 'نشط',
    inactif: 'غير نشط',
    brouillon: 'مسودة',
    envoye: 'مرسل',
    accepte: 'مقبول',
    refuse: 'مرفوض',
    expire: 'منتهي الصلاحية',
    tous: 'الكل',
    valide: 'مصادق عليه',
    echoue: 'فشل',
    rembourse: 'مسترد',
    en_cours: 'جاري',
    termine: 'منتهي',
    a_faire: 'مطلوب',
    bloque: 'معلق',

    total: 'المجموع',
    montant: 'المبلغ',
    date: 'التاريخ',
    statut: 'الحالة',
    nom: 'الاسم',
    prenom: 'الاسم الأول',
    email: 'البريد الإلكتروني',
    telephone: 'الهاتف',
    adresse: 'العنوان',
    description: 'الوصف',
    prix: 'السعر',
    quantite: 'الكمية',
    notes: 'ملاحظات',
    categorie: 'الفئة',
    mode_paiement: 'طريقة الدفع',
    source: 'المصدر',
    type: 'النوع',

    chargement: 'جاري التحميل...',
    aucune_donnee: 'لا توجد بيانات',
    erreur_serveur: 'خطأ في الخادم',
    succes: 'نجاح',
    confirmation_suppression: 'تأكيد الحذف؟',
    page: 'صفحة',
    filtrer_par: 'تصفية حسب',

    // الموردون
    gestion_fournisseurs: 'إدارة الموردين',
    gerer_fournisseurs: 'إدارة جميع مورديك',
    nouveau_fournisseur: 'مورد جديد',
    modifier_fournisseur: 'تعديل المورد',
    fournisseur_cree: 'تم إنشاء المورد بنجاح',
    fournisseur_modifie: 'تم تحديث المورد بنجاح',
    fournisseur_supprime: 'تم حذف المورد',
    liste_fournisseurs: 'قائمة الموردين',

    // العملاء
    gestion_clients: 'إدارة العملاء',
    gerer_clients: 'إدارة جميع عملائك',
    nouveau_client: 'عميل جديد',
    modifier_client: 'تعديل العميل',
    client_cree: 'تم إنشاء العميل بنجاح',
    client_modifie: 'تم تعديل العميل بنجاح',
    client_supprime: 'تم حذف العميل',
    choisir_client: 'اختر عميلاً',

    // الطلبات
    gestion_commandes: 'إدارة الطلبات',
    gerer_commandes: 'إدارة جميع طلبات شركتك',
    nouvelle_commande: 'طلب جديد',
    commande_cree: 'تم إنشاء الطلب بنجاح',
    commande_supprimee: 'تم حذف الطلب',
    liste_commandes: 'قائمة الطلبات',
    changer_statut: 'تغيير الحالة',
    payer: 'دفع',
    ajouter_produit: 'إضافة منتج',

    // عروض الأسعار
    gestion_devis: 'إدارة عروض الأسعار',
    gerer_devis: 'إدارة جميع عروض أسعارك',
    nouveau_devis: 'عرض سعر جديد',
    devis_cree: 'تم إنشاء عرض السعر بنجاح',
    devis_supprime: 'تم حذف عرض السعر',
    devis_converti: 'تم تحويل عرض السعر إلى طلب',
    liste_devis: 'قائمة عروض الأسعار',
    date_validite: 'تاريخ الصلاحية',
    convertir_commande: 'تحويل إلى طلب',
    remise: 'خصم (%)',
    notes_supplementaires: 'ملاحظات إضافية',

    // المستودعات
    gestion_entrepots: 'إدارة المستودعات',
    gerer_entrepots: 'إدارة مستودعاتك ومخزونها',
    nouvel_entrepot: 'مستودع جديد',
    modifier_entrepot: 'تعديل المستودع',
    entrepot_cree: 'تم إنشاء المستودع بنجاح',
    entrepot_modifie: 'تم تحديث المستودع بنجاح',
    entrepot_supprime: 'تم حذف المستودع',
    liste_entrepots: 'قائمة المستودعات',
    gestion_stock: 'إدارة المخزون',
    choisir_produit: 'اختر منتجاً',
    stock_actuel: 'المخزون الحالي',
    stock_vide: 'هذا المستودع فارغ.',
    gestion_produits: 'إدارة المنتجات',
    gerer_produits: 'إدارة كتالوج منتجاتك',
    nouveau_produit: 'منتج جديد',
    modifier_produit: 'تعديل المنتج',
    produit_cree: 'تم إنشاء المنتج بنجاح',
    produit_modifie: 'تم تحديث المنتج بنجاح',
    produit_supprime: 'تم حذف المنتج',
    catalogue_produits: 'كتالوج المنتجات',
    quantite_stock: 'كمية المخزون',
    rupture: 'نفاد المخزون',
    critique: 'حرج',
    bas: 'منخفض',
    normal: 'عادي',
    gestion_inventaires: 'إدارة الجرد',
    historique_stock: 'سجل المخزون',
    alerte_rupture: 'تنبيه نقص المخزون',
    transfert_stock: 'تحويل المخزون',
    entrepots_label: 'المستودعات',
    moteur_calcul: 'محرك الحساب',
    mouvements_stock: 'حركات المخزون',
    inventaire: 'الجرد',
    calculateur: 'آلة حاسبة',

    // لوحة القيادة
    bonjour: 'مرحباً',
    enregistres: 'مسجل',
    references: 'مراجع',
    aucune_alerte: 'لا توجد تنبيهات',
    produits_critiques: 'منتج(ات) حرجة',
    acces_rapide: 'وصول سريع',
    actualiser: 'تحديث',
    exporter_donnees: 'تصدير بياناتي',
    erreur_export: 'خطأ في التصدير',
    export_succes: 'تم تصدير البيانات بنجاح',
    promotions: 'العروض الترويجية',
    promotions_actives: 'العروض النشطة',
    actives: 'نشطة',
    alertes_stock: 'تنبيهات المخزون',
    achats_en_cours: 'المشتريات الجارية',
    gestion_documentaire: 'إدارة المستندات',
    archivage_numerique: 'الأرشفة الرقمية',
    gestion_acces: 'إدارة الوصول',
    alertes: 'تنبيهات',

    // انتهاء الفترة التجريبية
    essai_expire_titre: 'انتهت فترتك التجريبية المجانية',
    essai_expire_message: 'لقد استخدمت اتصالاتك المجانية الثلاثين',
    pour: 'لـ',
    essai_expire_donnees: 'لم يتم فقدان أي بيانات',
    essai_expire_conserve: 'كل ما أضفته يبقى محفوظاً.',
    exporter_mes_donnees: 'تصدير بياناتي',
    souscrire_abonnement: 'الاشتراك في خطة',
    erreur_export_donnees: 'تعذر تصدير بياناتك في الوقت الحالي.',

    // المالية
    gestion_finance: 'الإدارة المالية',
    gerer_finance: 'المحاسبة، المدفوعات، المصروفات والإيرادات',
    rapport: 'تقرير',
    depenses: 'المصروفات',
    recettes: 'الإيرادات',
    paiements: 'المدفوعات',
    filtrer_periode: 'تصفية حسب الفترة',
    date_debut: 'تاريخ البدء',
    date_fin: 'تاريخ الانتهاء',
    total_recettes: 'إجمالي الإيرادات',
    total_depenses: 'إجمالي المصروفات',
    resultat_net: 'النتيجة الصافية',
    detail_recettes: 'تفاصيل الإيرادات',
    commandes_livrees: 'الطلبات المسلمة',
    recettes_manuelles: 'الإيرادات اليدوية',
    depenses_par_categorie: 'المصروفات حسب الفئة',
    aucune_depense: 'لا توجد مصروفات مسجلة لهذه الفترة.',
    nouvelle_depense: 'مصروف جديد',
    liste_depenses: 'قائمة المصروفات',
    modifier_depense: 'تعديل المصروف',
    depense_cree: 'تم تسجيل المصروف بنجاح',
    depense_modifiee: 'تم تحديث المصروف بنجاح',
    depense_supprimee: 'تم حذف المصروف',
    nouvelle_recette: 'إيراد جديد',
    liste_recettes: 'قائمة الإيرادات',
    recette_cree: 'تم تسجيل الإيراد بنجاح',
    recette_supprimee: 'تم حذف الإيراد',
    exemple_source: 'مثال: منحة، استرداد...',
    enregistrer_paiement: 'تسجيل دفعة',
    liste_paiements: 'قائمة المدفوعات',
    numero_transaction: 'رقم المعاملة',
    commande: 'طلب',
    achat: 'شراء',
    nouveau_paiement: 'دفعة جديدة',
    type_reference: 'نوع المرجع',
    commande_client: 'طلب العميل',
    achat_fournisseur: 'شراء المورد',
    id_reference: 'معرف المرجع',
    paiement_attention: 'طرق الدفع Stripe و PayPal و Flouci و Konnect تنشئ دفعة "قيد الانتظار" حتى تأكيد مزود الدفع.',
    paiement_cree: 'تم تسجيل الدفعة',
    statut_paiement_modifie: 'تم تحديث حالة الدفعة',

    // Auth
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    password: 'كلمة المرور',
    forgot_password: 'نسيت كلمة المرور؟',
    create_account: 'إنشاء حساب شركة',
    or: 'أو',
    all_rights_reserved: 'جميع الحقوق محفوظة',
    erreur_connexion: 'خطأ في الاتصال',
    email_ou_password_incorrect: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',

    bienvenue: 'مرحباً',
    espace_client: 'مساحة العميل',
    profil: 'الملف الشخصي',
    factures: 'الفواتير',
    securite_mfa: 'أمان MFA',

  // ar (valeurs arabes)
    login_titre: 'منصة إدارة الأعمال',
    email_professionnel: 'البريد الإلكتروني المهني',
    mot_de_passe: 'كلمة المرور',
    connexion_en_cours: 'جاري تسجيل الدخول...',
    se_connecter: 'تسجيل الدخول',
    mot_de_passe_oublie: 'نسيت كلمة المرور؟',
    creer_compte_entreprise: 'إنشاء حساب شركة',
    deja_compte: 'لديك حساب بالفعل؟ سجل الدخول',
    tous_droits_reserves: 'جميع الحقوق محفوظة',
    creer_mon_compte: 'إنشاء حسابي',
    inscrire_entreprise: 'سجل شركتك في دقائق معدودة',
    infos_entreprise: 'معلومات الشركة',
    nom_entreprise: 'اسم الشركة',
    compte_administrateur: 'حساب المسؤول',
    choisir_formule: 'اختر باقتك',
    essai_gratuit: 'تجربة مجانية',
    connexions_gratuites: '30 تسجيل دخول مجاني',
    sans_engagement: 'بدون التزام',
    abonnement: 'اشتراك',
    acces_illimite: 'وصول غير محدود',
    inscription_en_cours: 'جاري التسجيل...',
    sinscrire: 'إنشاء حساب',

    alertes_rupture_stock: 'تنبيهات نفاد المخزون',
    surveillez_produits_risque: 'راقب المنتجات المعرضة للخطر',
    rafraichir: 'تحديث',
    produits_en_alerte: 'منتجات في حالة تنبيه',
    en_rupture_totale: 'نفاد تام',
    pas_alerte_rupture: 'لا توجد تنبيهات نفاد',
    tous_produits_stock_suffisant: 'جميع منتجاتك لديها مخزون كافٍ.',
    commander: 'طلب',
    stock_actuel_label: 'المخزون الحالي',
    niveau: 'المستوى',
    rupture_totale: 'نفاد',
    tres_critique: 'حرج جداً',
    critique_niveau: 'حرج',
    bas_niveau: 'منخفض',

    historique_mouvements: 'اطلع على سجل الحركات لكل منتج',
    ajuster_stock: 'تعديل المخزون',
    selectionner_produit_titre: 'اختر منتجاً',
    choisir_produit_placeholder: '-- اختر منتجاً --',
    quantite_entree_sortie: 'الكمية (+ دخول، - خروج) *',
    motif_ajustement: 'السبب *',
    raison_ajustement: 'سبب التعديل',
    appliquer_ajustement: 'تطبيق التعديل',
    historique_mouvements_produit: 'سجل الحركات',
    type: 'النوع',
    ancien_stock: 'المخزون السابق',
    nouveau_stock: 'المخزون الجديد',
    par: 'بواسطة',
    entree: 'دخول',
    sortie: 'خروج',
    ajustement: 'تعديل',
    commande_client_type: 'طلب عميل',
    achat_fournisseur_type: 'شراء من مورد',
    stock_ajuste_succes: 'تم تعديل المخزون بنجاح',

    transfert_stock_titre: 'تحويل المخزون',
    transferer_stock_desc: 'حوّل المخزون من مستودع إلى آخر',
    acces_refuse_titre: 'الوصول مرفوض',
    pas_permission_transfert: 'ليس لديك صلاحية تحويل المخزون.',
    nouveau_transfert: 'تحويل جديد',
    entrepot_source: 'المستودع المصدر *',
    entrepot_destination: 'المستودع الوجهة *',
    source_placeholder: '-- المصدر --',
    destination_placeholder: '-- الوجهة --',
    stock_disponible: 'المخزون المتاح',
    aucun_stock: 'لا يوجد مخزون',
    ajoutez_stock_source: 'أضف مخزوناً إلى المستودع المصدر أولاً',
    effectuer_transfert: 'تنفيذ التحويل',
    transfert_en_cours: 'جارٍ التحويل...',
    transfert_effectue: 'تم التحويل بنجاح',
    stock_insuffisant: 'المخزون غير كافٍ',
    quantite_superieure_zero: 'يجب أن تكون الكمية أكبر من 0',
    produit_sans_stock_source: 'هذا المنتج ليس له مخزون في المستودع المصدر المحدد.',
  }

};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app-language') || 'fr';
  });
  const [dir, setDir] = useState('ltr');

  useEffect(() => {
    localStorage.setItem('app-language', language);
    const newDir = language === 'ar' ? 'rtl' : 'ltr';
    setDir(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
  }, [language]);

  // t() cherche d'abord dans la langue courante, puis retombe sur le
  // français si la clé est absente (au lieu de renvoyer la clé brute),
  // et enfin sur la clé elle-même en tout dernier recours.
  const t = (key) => {
    return (
      translations[language]?.[key] ??
      translations.fr?.[key] ??
      key
    );
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, dir, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);