import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    clients: 'Clients',
    fournisseurs: 'Fournisseurs',
    produits: 'Produits',
    commandes: 'Commandes',
    devis: 'Devis',
    achats: 'Achats',
    stock: 'Stock',
    finance: 'Finance',
    utilisateurs: 'Utilisateurs',
    documents: 'Documents',
    archives: 'Archives',
    notifications: 'Notifications',
    parametres: 'Paramètres',
    deconnexion: 'Déconnexion',

    // Sections
    navigation: 'Navigation',
    ventes: 'Ventes',
    stock: 'Stock',
    finance: 'Finance',
    administration: 'Administration',

    // Actions
    creer: 'Créer',
    modifier: 'Modifier',
    supprimer: 'Supprimer',
    valider: 'Valider',
    annuler: 'Annuler',
    enregistrer: 'Enregistrer',
    rechercher: 'Rechercher',
    exporter: 'Exporter',
    imprimer: 'Imprimer',
    telecharger: 'Télécharger',
    retour: 'Retour',
    actions: 'Actions',

    // États
    en_attente: 'En attente',
    confirmee: 'Confirmée',
    livree: 'Livrée',
    annulee: 'Annulée',
    actif: 'Actif',
    inactif: 'Inactif',
    brouillon: 'Brouillon',
    envoye: 'Envoyé',
    accepte: 'Accepté',
    refuse: 'Refusé',
    expire: 'Expiré',
    tous: 'Tous',

    // Général
    total: 'Total',
    montant: 'Montant',
    date: 'Date',
    statut: 'Statut',
    nom: 'Nom',
    email: 'Email',
    telephone: 'Téléphone',
    adresse: 'Adresse',
    description: 'Description',
    prix: 'Prix',
    quantite: 'Quantité',

    // Messages
    chargement: 'Chargement...',
    aucune_donnee: 'Aucune donnée',
    erreur_serveur: 'Erreur serveur',
    succes: 'Succès',
    confirmation_suppression: 'Confirmer la suppression ?',

    // Module commercial
    gestion_clients: 'Gestion des clients',
    gerer_clients: 'Gérez tous vos clients',
    nouveau_client: 'Nouveau client',
    modifier_client: 'Modifier le client',
    client_cree: 'Client créé avec succès',
    client_modifie: 'Client modifié avec succès',
    client_supprime: 'Client supprimé',

    // Module financier
    gestion_finance: 'Gestion financière',
    depenses: 'Dépenses',
    recettes: 'Recettes',
    paiements: 'Paiements',
    nouvelle_depense: 'Nouvelle dépense',
    nouvelle_recette: 'Nouvelle recette',

    // Module stock
    gestion_stock: 'Gestion de stock',
    inventaire: 'Inventaire',
    mouvements_stock: 'Mouvements de stock',
    alerte_rupture: 'Alerte de rupture',
    transfert_stock: 'Transfert de stock',
    entrepots: 'Entrepôts',

    // Module Ventes
    gestion_commandes: 'Gestion des commandes',
    nouvelle_commande: 'Nouvelle commande',
    commande_cree: 'Commande créée avec succès',
    promotions: 'Promotions',
    paiement_en_ligne: 'Paiement en ligne',

    // Module Achats
    gestion_achats: 'Gestion des achats',
    nouveau_achat: 'Nouvel achat',
    paiement_fournisseur: 'Paiement fournisseur',

    // Pages
    bienvenue: 'Bienvenue',
    espace_client: 'Espace client',
    profil: 'Profil',
    factures: 'Factures',
    securite_mfa: 'Sécurité MFA',
    calculateur: 'Calculateur',

    // Erreurs
    erreur_connexion: 'Erreur de connexion',
    email_ou_password_incorrect: 'Email ou mot de passe incorrect',
    filtrer_par: 'Filtrer par',
    page: 'Page',

    // Auth
    login: 'Se connecter',
    register: "S'inscrire",
    password: 'Mot de passe',
    forgot_password: 'Mot de passe oublié ?',
    create_account: 'Créer un compte entreprise',
    or: 'ou',
    all_rights_reserved: 'Tous droits réservés',

    // AJOUT DES CLÉS MANQUANTES POUR LE TABLEAU DE BORD
    exporter_donnees: 'Exporter mes données',
    erreur_export: 'Erreur lors de l\'export',
    acces_rapide: 'Accès rapide',
    actualiser: 'Actualiser',
    bonjour: 'Bonjour',
    enregistres: 'enregistrés',
    en_cours: 'en cours',
    references: 'références',
    aucune_alerte: 'Aucune alerte',
    produits_critiques: 'produit(s) critique(s)',
    gestion_entrepots: 'Gestion des entrepôts',
    moteur_calcul: 'Moteur de calcul',
    gestion_documentaire: 'Gestion documentaire',
    archivage_numerique: 'Archivage numérique',
    gestion_acces: 'Gestion des accès',
    promotions_actives: 'Promotions actives',
    alertes_stock: 'Alertes stock',
    rupture: 'rupture',
    achats_en_cours: 'Achats en cours',
    jours_restants: 'jours restants',
    connexions_restantes: 'connexion(s) restante(s)',
    periode_essai: 'Période d\'essai gratuite',
    avant_expiration: 'avant expiration',
    tableau_de_bord: 'Tableau de bord',
    accueil: 'Accueil',
    bienvenue_retour: 'Bienvenue',
    statistiques: 'Statistiques',
    vue_ensemble: 'Vue d\'ensemble',
    activite_recente: 'Activité récente',
    voir_tout: 'Voir tout',
    aucun_enregistrement: 'Aucun enregistrement',
    chargement_en_cours: 'Chargement en cours...',
    erreur_chargement: 'Erreur de chargement',
    reessayer: 'Réessayer',
    filtre: 'Filtre',
    trier_par: 'Trier par',
    ordre_croissant: 'Croissant',
    ordre_decroissant: 'Décroissant',
    recherche_avancee: 'Recherche avancée',
    effacer_filtres: 'Effacer les filtres',
    appliquer: 'Appliquer',
    fermer: 'Fermer',
    ouvrir: 'Ouvrir',
    details: 'Détails',
    resume: 'Résumé',
    rapport: 'Rapport',
    generation_rapport: 'Génération du rapport',
    rapport_genere: 'Rapport généré avec succès',
    erreur_generation: 'Erreur lors de la génération du rapport',
    format_pdf: 'Format PDF',
    format_excel: 'Format Excel',
    format_csv: 'Format CSV',
    format_json: 'Format JSON',
    depuis: 'Depuis',
    jusqua: 'Jusqu\'à',
    selectionner_periode: 'Sélectionner une période',
    aujourdhui: 'Aujourd\'hui',
    cette_semaine: 'Cette semaine',
    ce_mois: 'Ce mois',
    cette_annee: 'Cette année',
    personnalise: 'Personnalisé',
    nombre_total: 'Nombre total',
    moyenne: 'Moyenne',
    minimum: 'Minimum',
    maximum: 'Maximum',
    evolution: 'Évolution',
    tendance: 'Tendance',
    stable: 'Stable',
    hausse: 'Hausse',
    baisse: 'Baisse',
    objectif: 'Objectif',
    atteint: 'Atteint',
    non_atteint: 'Non atteint',
    en_progression: 'En progression',
    en_regression: 'En régression',
    performance: 'Performance',
    classement: 'Classement',
    top_ventes: 'Top ventes',
    meilleurs_clients: 'Meilleurs clients',
    produits_populaires: 'Produits populaires',
    stock_critique: 'Stock critique',
    commandes_recentes: 'Commandes récentes',
    factures_impayees: 'Factures impayées',
    rappels: 'Rappels',
    echeances: 'Échéances',
    calendrier: 'Calendrier',
    agenda: 'Agenda',
    taches: 'Tâches',
    priorite: 'Priorité',
    haute: 'Haute',
    moyenne: 'Moyenne',
    basse: 'Basse',
    terminee: 'Terminée',
    en_cours: 'En cours',
    a_faire: 'À faire',
    bloque: 'Bloqué',
    annule: 'Annulé',
    notes: 'Notes',
    commentaires: 'Commentaires',
    piece_jointe: 'Pièce jointe',
    fichier: 'Fichier',
    image: 'Image',
    document: 'Document',
    lien: 'Lien',
    partager: 'Partager',
    collaborer: 'Collaborer',
    equipe: 'Équipe',
    membre: 'Membre',
    inviter: 'Inviter',
    accepter: 'Accepter',
    refuser: 'Refuser',
    en_attente: 'En attente',
    approuve: 'Approuvé',
    rejete: 'Rejeté',
    soumis: 'Soumis',
    en_revision: 'En révision',
    approuver: 'Approuver',
    rejeter: 'Rejeter',
    soumettre: 'Soumettre',
    revision: 'Révision',
    valide: 'Valide',
    invalide: 'Invalide',
    complet: 'Complet',
    incomplet: 'Incomplet',
    disponible: 'Disponible',
    indisponible: 'Indisponible',
    reserve: 'Réservé',
    occupe: 'Occupé',
    libre: 'Libre',
    ferme: 'Fermé',
    ouvert: 'Ouvert',
    en_cours: 'En cours',
    termine: 'Terminé',
    annule: 'Annulé',
    reporte: 'Reporté',
    differe: 'Différé',
    urgent: 'Urgent',
    normal: 'Normal',
    faible: 'Faible',
    critique: 'Critique',
    optimal: 'Optimal',
    satisfaisant: 'Satisfaisant',
    insuffisant: 'Insuffisant',
    excellent: 'Excellent',
    bon: 'Bon',
    moyen: 'Moyen',
    mauvais: 'Mauvais'
  },

  en: {
    // Navigation
    dashboard: 'Dashboard',
    clients: 'Clients',
    fournisseurs: 'Suppliers',
    produits: 'Products',
    commandes: 'Orders',
    devis: 'Quotes',
    achats: 'Purchases',
    stock: 'Stock',
    finance: 'Finance',
    utilisateurs: 'Users',
    documents: 'Documents',
    archives: 'Archives',
    notifications: 'Notifications',
    parametres: 'Settings',
    deconnexion: 'Logout',

    // Sections
    navigation: 'Navigation',
    ventes: 'Sales',
    stock: 'Stock',
    finance: 'Finance',
    administration: 'Administration',

    // Actions
    creer: 'Create',
    modifier: 'Edit',
    supprimer: 'Delete',
    valider: 'Validate',
    annuler: 'Cancel',
    enregistrer: 'Save',
    rechercher: 'Search',
    exporter: 'Export',
    imprimer: 'Print',
    telecharger: 'Download',
    retour: 'Back',
    actions: 'Actions',

    // États
    en_attente: 'Pending',
    confirmee: 'Confirmed',
    livree: 'Delivered',
    annulee: 'Cancelled',
    actif: 'Active',
    inactif: 'Inactive',
    brouillon: 'Draft',
    envoye: 'Sent',
    accepte: 'Accepted',
    refuse: 'Refused',
    expire: 'Expired',
    tous: 'All',

    // Général
    total: 'Total',
    montant: 'Amount',
    date: 'Date',
    statut: 'Status',
    nom: 'Name',
    email: 'Email',
    telephone: 'Phone',
    adresse: 'Address',
    description: 'Description',
    prix: 'Price',
    quantite: 'Quantity',

    // Messages
    chargement: 'Loading...',
    aucune_donnee: 'No data',
    erreur_serveur: 'Server error',
    succes: 'Success',
    confirmation_suppression: 'Confirm deletion?',

    // Module commercial
    gestion_clients: 'Client management',
    gerer_clients: 'Manage all your clients',
    nouveau_client: 'New client',
    modifier_client: 'Edit client',
    client_cree: 'Client created successfully',
    client_modifie: 'Client updated successfully',
    client_supprime: 'Client deleted',

    // Module financier
    gestion_finance: 'Financial management',
    depenses: 'Expenses',
    recettes: 'Revenue',
    paiements: 'Payments',
    nouvelle_depense: 'New expense',
    nouvelle_recette: 'New revenue',

    // Module stock
    gestion_stock: 'Stock management',
    inventaire: 'Inventory',
    mouvements_stock: 'Stock movements',
    alerte_rupture: 'Stock alert',
    transfert_stock: 'Stock transfer',
    entrepots: 'Warehouses',

    // Module Ventes
    gestion_commandes: 'Order management',
    nouvelle_commande: 'New order',
    commande_cree: 'Order created successfully',
    promotions: 'Promotions',
    paiement_en_ligne: 'Online Payment',

    // Module Achats
    gestion_achats: 'Purchase management',
    nouveau_achat: 'New purchase',
    paiement_fournisseur: 'Supplier Payment',

    // Pages
    bienvenue: 'Welcome',
    espace_client: 'Client space',
    profil: 'Profile',
    factures: 'Invoices',
    securite_mfa: 'MFA Security',
    calculateur: 'Calculator',

    // Erreurs
    erreur_connexion: 'Connection error',
    email_ou_password_incorrect: 'Invalid email or password',
    filtrer_par: 'Filter by',
    page: 'Page',

    // Auth
    login: 'Login',
    register: 'Register',
    password: 'Password',
    forgot_password: 'Forgot password?',
    create_account: 'Create company account',
    or: 'or',
    all_rights_reserved: 'All rights reserved',

    
    // AJOUT DES CLÉS MANQUANTES POUR LE TABLEAU DE BORD - ENGLISH
    exporter_donnees: 'Export my data',
    erreur_export: 'Export error',
    acces_rapide: 'Quick access',
    actualiser: 'Refresh',
    bonjour: 'Hello',
    enregistres: 'recorded',
    en_cours: 'in progress',
    references: 'references',
    aucune_alerte: 'No alerts',
    produits_critiques: 'critical product(s)',
    gestion_entrepots: 'Warehouse management',
    moteur_calcul: 'Calculation engine',
    gestion_documentaire: 'Document management',
    archivage_numerique: 'Digital archiving',
    gestion_acces: 'Access management',
    promotions_actives: 'Active promotions',
    alertes_stock: 'Stock alerts',
    rupture: 'out of stock',
    achats_en_cours: 'Purchases in progress',
    jours_restants: 'days remaining',
    connexions_restantes: 'connection(s) remaining',
    periode_essai: 'Free trial period',
    avant_expiration: 'before expiration',
    tableau_de_bord: 'Dashboard',
    accueil: 'Home',
    bienvenue_retour: 'Welcome back',
    statistiques: 'Statistics',
    vue_ensemble: 'Overview',
    activite_recente: 'Recent activity',
    voir_tout: 'View all',
    aucun_enregistrement: 'No records',
    chargement_en_cours: 'Loading...',
    erreur_chargement: 'Loading error',
    reessayer: 'Retry',
    filtre: 'Filter',
    trier_par: 'Sort by',
    ordre_croissant: 'Ascending',
    ordre_decroissant: 'Descending',
    recherche_avancee: 'Advanced search',
    effacer_filtres: 'Clear filters',
    appliquer: 'Apply',
    fermer: 'Close',
    ouvrir: 'Open',
    details: 'Details',
    resume: 'Summary',
    rapport: 'Report',
    generation_rapport: 'Report generation',
    rapport_genere: 'Report generated successfully',
    erreur_generation: 'Error generating report',
    format_pdf: 'PDF format',
    format_excel: 'Excel format',
    format_csv: 'CSV format',
    format_json: 'JSON format',
    depuis: 'From',
    jusqua: 'To',
    selectionner_periode: 'Select period',
    aujourdhui: 'Today',
    cette_semaine: 'This week',
    ce_mois: 'This month',
    cette_annee: 'This year',
    personnalise: 'Custom',
    nombre_total: 'Total number',
    moyenne: 'Average',
    minimum: 'Minimum',
    maximum: 'Maximum',
    evolution: 'Evolution',
    tendance: 'Trend',
    stable: 'Stable',
    hausse: 'Rising',
    baisse: 'Falling',
    objectif: 'Goal',
    atteint: 'Achieved',
    non_atteint: 'Not achieved',
    en_progression: 'Progressing',
    en_regression: 'Regressing',
    performance: 'Performance',
    classement: 'Ranking',
    top_ventes: 'Top sales',
    meilleurs_clients: 'Best clients',
    produits_populaires: 'Popular products',
    stock_critique: 'Critical stock',
    commandes_recentes: 'Recent orders',
    factures_impayees: 'Unpaid invoices',
    rappels: 'Reminders',
    echeances: 'Deadlines',
    calendrier: 'Calendar',
    agenda: 'Agenda',
    taches: 'Tasks',
    priorite: 'Priority',
    haute: 'High',
    moyenne: 'Medium',
    basse: 'Low',
    terminee: 'Completed',
    a_faire: 'To do',
    bloque: 'Blocked',
    notes: 'Notes',
    commentaires: 'Comments',
    piece_jointe: 'Attachment',
    fichier: 'File',
    image: 'Image',
    document: 'Document',
    lien: 'Link',
    partager: 'Share',
    collaborer: 'Collaborate',
    equipe: 'Team',
    membre: 'Member',
    inviter: 'Invite',
    accepter: 'Accept',
    refuser: 'Refuse',
    approuve: 'Approved',
    rejete: 'Rejected',
    soumis: 'Submitted',
    en_revision: 'Under review',
    approuver: 'Approve',
    rejeter: 'Reject',
    soumettre: 'Submit',
    revision: 'Review',
    valide: 'Valid',
    invalide: 'Invalid',
    complet: 'Complete',
    incomplet: 'Incomplete',
    disponible: 'Available',
    indisponible: 'Unavailable',
    reserve: 'Reserved',
    occupe: 'Occupied',
    libre: 'Free',
    ferme: 'Closed',
    ouvert: 'Open',
    termine: 'Finished',
    reporte: 'Postponed',
    differe: 'Deferred',
    urgent: 'Urgent',
    normal: 'Normal',
    faible: 'Low',
    critique: 'Critical',
    optimal: 'Optimal',
    satisfaisant: 'Satisfactory',
    insuffisant: 'Insufficient',
    excellent: 'Excellent',
    bon: 'Good',
    moyen: 'Average',
    mauvais: 'Bad'
  },

  ar: {
    // Navigation
    dashboard: 'لوحة القيادة',
    clients: 'العملاء',
    fournisseurs: 'الموردون',
    produits: 'المنتجات',
    commandes: 'الطلبات',
    devis: 'عروض الأسعار',
    achats: 'المشتريات',
    stock: 'المخزون',
    finance: 'المالية',
    utilisateurs: 'المستخدمون',
    documents: 'المستندات',
    archives: 'الأرشيف',
    notifications: 'الإشعارات',
    parametres: 'الإعدادات',
    deconnexion: 'تسجيل الخروج',

    // Sections
    navigation: 'التنقل',
    ventes: 'المبيعات',
    stock: 'المخزون',
    finance: 'المالية',
    administration: 'الإدارة',

    // Actions
    creer: 'إنشاء',
    modifier: 'تعديل',
    supprimer: 'حذف',
    valider: 'تأكيد',
    annuler: 'إلغاء',
    enregistrer: 'حفظ',
    rechercher: 'بحث',
    exporter: 'تصدير',
    imprimer: 'طباعة',
    telecharger: 'تحميل',
    retour: 'رجوع',
    actions: 'إجراءات',

    // États
    en_attente: 'قيد الانتظار',
    confirmee: 'مؤكد',
    livree: 'تم التسليم',
    annulee: 'ملغى',
    actif: 'نشط',
    inactif: 'غير نشط',
    brouillon: 'مسودة',
    envoye: 'مرسل',
    accepte: 'مقبول',
    refuse: 'مرفوض',
    expire: 'منتهي الصلاحية',
    tous: 'الكل',

    // Général
    total: 'المجموع',
    montant: 'المبلغ',
    date: 'التاريخ',
    statut: 'الحالة',
    nom: 'الاسم',
    email: 'البريد الإلكتروني',
    telephone: 'الهاتف',
    adresse: 'العنوان',
    description: 'الوصف',
    prix: 'السعر',
    quantite: 'الكمية',

    // Messages
    chargement: 'جاري التحميل...',
    aucune_donnee: 'لا توجد بيانات',
    erreur_serveur: 'خطأ في الخادم',
    succes: 'نجاح',
    confirmation_suppression: 'تأكيد الحذف؟',

    // Module commercial
    gestion_clients: 'إدارة العملاء',
    gerer_clients: 'إدارة جميع عملائك',
    nouveau_client: 'عميل جديد',
    modifier_client: 'تعديل العميل',
    client_cree: 'تم إنشاء العميل بنجاح',
    client_modifie: 'تم تعديل العميل بنجاح',
    client_supprime: 'تم حذف العميل',

    // Module financier
    gestion_finance: 'الإدارة المالية',
    depenses: 'المصروفات',
    recettes: 'الإيرادات',
    paiements: 'المدفوعات',
    nouvelle_depense: 'مصروف جديد',
    nouvelle_recette: 'إيراد جديد',

    // Module stock
    gestion_stock: 'إدارة المخزون',
    inventaire: 'الجرد',
    mouvements_stock: 'حركات المخزون',
    alerte_rupture: 'تنبيه نقص المخزون',
    transfert_stock: 'تحويل المخزون',
    entrepots: 'المستودعات',

    // Module Ventes
    gestion_commandes: 'إدارة الطلبات',
    nouvelle_commande: 'طلب جديد',
    commande_cree: 'تم إنشاء الطلب بنجاح',
    promotions: 'العروض الترويجية',
    paiement_en_ligne: 'الدفع عبر الإنترنت',

    // Module Achats
    gestion_achats: 'إدارة المشتريات',
    nouveau_achat: 'شراء جديد',
    paiement_fournisseur: 'دفع المورد',

    // Pages
    bienvenue: 'مرحباً',
    espace_client: 'مساحة العميل',
    profil: 'الملف الشخصي',
    factures: 'الفواتير',
    securite_mfa: 'أمان MFA',
    calculateur: 'آلة حاسبة',

    // Erreurs
    erreur_connexion: 'خطأ في الاتصال',
    email_ou_password_incorrect: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    filtrer_par: 'تصفية حسب',
    page: 'صفحة',

    // Auth
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب',
    password: 'كلمة المرور',
    forgot_password: 'نسيت كلمة المرور؟',
    create_account: 'إنشاء حساب شركة',
    or: 'أو',
    all_rights_reserved: 'جميع الحقوق محفوظة',

    // ============================================================
    // AJOUT DES CLÉS MANQUANTES POUR LE TABLEAU DE BORD - ARABIC
    // ============================================================
    exporter_donnees: 'تصدير بياناتي',
    erreur_export: 'خطأ في التصدير',
    acces_rapide: 'وصول سريع',
    actualiser: 'تحديث',
    bonjour: 'مرحباً',
    enregistres: 'مسجل',
    en_cours: 'جاري',
    references: 'مراجع',
    aucune_alerte: 'لا توجد تنبيهات',
    produits_critiques: 'منتج(ات) حرجة',
    gestion_entrepots: 'إدارة المستودعات',
    moteur_calcul: 'محرك الحساب',
    gestion_documentaire: 'إدارة المستندات',
    archivage_numerique: 'الأرشفة الرقمية',
    gestion_acces: 'إدارة الوصول',
    promotions_actives: 'العروض النشطة',
    alertes_stock: 'تنبيهات المخزون',
    rupture: 'نفاد المخزون',
    achats_en_cours: 'المشتريات الجارية',
    jours_restants: 'أيام متبقية',
    connexions_restantes: 'اتصال(ات) متبقية',
    periode_essai: 'فترة تجريبية مجانية',
    avant_expiration: 'قبل انتهاء الصلاحية',
    tableau_de_bord: 'لوحة القيادة',
    accueil: 'الرئيسية',
    bienvenue_retour: 'مرحباً بعودتك',
    statistiques: 'إحصائيات',
    vue_ensemble: 'نظرة عامة',
    activite_recente: 'النشاط الأخير',
    voir_tout: 'عرض الكل',
    aucun_enregistrement: 'لا توجد سجلات',
    chargement_en_cours: 'جاري التحميل...',
    erreur_chargement: 'خطأ في التحميل',
    reessayer: 'إعادة المحاولة',
    filtre: 'فلتر',
    trier_par: 'ترتيب حسب',
    ordre_croissant: 'تصاعدي',
    ordre_decroissant: 'تنازلي',
    recherche_avancee: 'بحث متقدم',
    effacer_filtres: 'مسح الفلاتر',
    appliquer: 'تطبيق',
    fermer: 'إغلاق',
    ouvrir: 'فتح',
    details: 'تفاصيل',
    resume: 'ملخص',
    rapport: 'تقرير',
    generation_rapport: 'إنشاء التقرير',
    rapport_genere: 'تم إنشاء التقرير بنجاح',
    erreur_generation: 'خطأ في إنشاء التقرير',
    format_pdf: 'صيغة PDF',
    format_excel: 'صيغة Excel',
    format_csv: 'صيغة CSV',
    format_json: 'صيغة JSON',
    depuis: 'من',
    jusqua: 'إلى',
    selectionner_periode: 'اختر فترة',
    aujourdhui: 'اليوم',
    cette_semaine: 'هذا الأسبوع',
    ce_mois: 'هذا الشهر',
    cette_annee: 'هذه السنة',
    personnalise: 'مخصص',
    nombre_total: 'العدد الإجمالي',
    moyenne: 'المتوسط',
    minimum: 'الحد الأدنى',
    maximum: 'الحد الأقصى',
    evolution: 'التطور',
    tendance: 'الاتجاه',
    stable: 'مستقر',
    hausse: 'ارتفاع',
    baisse: 'انخفاض',
    objectif: 'الهدف',
    atteint: 'تم تحقيقه',
    non_atteint: 'لم يتم تحقيقه',
    en_progression: 'في تقدم',
    en_regression: 'في تراجع',
    performance: 'الأداء',
    classement: 'الترتيب',
    top_ventes: 'أفضل المبيعات',
    meilleurs_clients: 'أفضل العملاء',
    produits_populaires: 'المنتجات الأكثر شهرة',
    stock_critique: 'مخزون حرج',
    commandes_recentes: 'الطلبات الأخيرة',
    factures_impayees: 'فواتير غير مدفوعة',
    rappels: 'تذكيرات',
    echeances: 'مواعيد استحقاق',
    calendrier: 'تقويم',
    agenda: 'جدول أعمال',
    taches: 'مهام',
    priorite: 'أولوية',
    haute: 'عالية',
    moyenne: 'متوسطة',
    basse: 'منخفضة',
    terminee: 'مكتملة',
    a_faire: 'مطلوب',
    bloque: 'معلق',
    notes: 'ملاحظات',
    commentaires: 'تعليقات',
    piece_jointe: 'مرفق',
    fichier: 'ملف',
    image: 'صورة',
    document: 'مستند',
    lien: 'رابط',
    partager: 'مشاركة',
    collaborer: 'تعاون',
    equipe: 'فريق',
    membre: 'عضو',
    inviter: 'دعوة',
    accepter: 'قبول',
    refuser: 'رفض',
    approuve: 'موافق عليه',
    rejete: 'مرفوض',
    soumis: 'مرسل',
    en_revision: 'قيد المراجعة',
    approuver: 'الموافقة',
    rejeter: 'الرفض',
    soumettre: 'إرسال',
    revision: 'مراجعة',
    valide: 'صالح',
    invalide: 'غير صالح',
    complet: 'كامل',
    incomplet: 'غير كامل',
    disponible: 'متاح',
    indisponible: 'غير متاح',
    reserve: 'محجوز',
    occupe: 'مشغول',
    libre: 'فارغ',
    ferme: 'مغلق',
    ouvert: 'مفتوح',
    termine: 'منتهي',
    reporte: 'مؤجل',
    differe: 'مؤخر',
    urgent: 'عاجل',
    normal: 'عادي',
    faible: 'ضعيف',
    critique: 'حرج',
    optimal: 'أمثل',
    satisfaisant: 'مرضٍ',
    insuffisant: 'غير كافٍ',
    excellent: 'ممتاز',
    bon: 'جيد',
    moyen: 'متوسط',
    mauvais: 'سيئ'
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('app-language') || 'fr';
  });
  const [dir, setDir] = useState('ltr');

  useEffect(() => {
    localStorage.setItem('app-language', language);
    const newDir = language === 'ar' ? 'rtl' : 'ltr';
    setDir(newDir);
    document.documentElement.dir = newDir;
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
    }
  };

  return (
    <LanguageContext.Provider value={{ language, dir, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);